export enum LimitedType {
  PERMANENT = 'PERMANENT',
  LIMITED = 'LIMITED',
  SPRING_LIMITED = 'SPRING_LIMITED',
  SUMMER_LIMITED = 'SUMMER_LIMITED',
  AUTUMN_LIMITED = 'AUTUMN_LIMITED',
  WINTER_LIMITED = 'WINTER_LIMITED',
  BIRTHDAY_LIMITED = 'BIRTHDAY_LIMITED',
  LEG_LIMITED = 'LEG_LIMITED',
  SHUFFLE_LIMITED = 'SHUFFLE_LIMITED',
  BATTLE_LIMITED = 'BATTLE_LIMITED',
  PARTY_LIMITED = 'PARTY_LIMITED',
  ACTIVITY_LIMITED = 'ACTIVITY_LIMITED',
  BANGDREAM_LIMITED = 'BANGDREAM_LIMITED',
  GRADUATE_LIMITED = 'GRADUATE_LIMITED',
  LOGIN_BONUS = 'LOGIN_BONUS',
  REWARD = 'REWARD',
}

export type LimitedTypeValue = (typeof LimitedType)[keyof typeof LimitedType];
